"""user must change password

Revision ID: 5691cb8ff945
Revises: 9992e2b4882f
Create Date: 2026-10-07 01:40:47.743856

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5691cb8ff945"
down_revision: str | Sequence[str] | None = "9992e2b4882f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("must_change_password", sa.Boolean(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "must_change_password")
    # ### end Alembic commands ###
