"""quote cache

Revision ID: 9992e2b4882f
Revises: 72ae4f6e3168
Create Date: 2026-10-07 01:28:48.817947

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9992e2b4882f"
down_revision: str | Sequence[str] | None = "72ae4f6e3168"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quote_cache",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("price", sa.Text(), nullable=False),
        sa.Column("prev_close", sa.Text(), nullable=True),
        sa.Column("quote_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("symbol"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quote_cache")
    # ### end Alembic commands ###
